import type { MemorySeed } from '../data/memory/memory-context';
import { createDefaultPreferences } from '../a11y/preferences';

/**
 * Demo-Daten.
 *
 * Alle Personen sind frei erfunden. Die Namen tragen absichtlich den Zusatz
 * "(Demo)", damit im Betrieb sofort auffaellt, wenn Testdaten in eine
 * echte Umgebung geraten. Es sind keine realen Gesundheitsangaben enthalten;
 * die Bedarfe sind alltagsnah und bewusst unspezifisch formuliert.
 */

const NOW = '2026-03-02T09:00:00.000Z';

export const DEMO_NOW = NOW;

export const demoSeed: MemorySeed = {
  users: [
    {
      id: 'u_seeker_1',
      displayName: 'Frau Kessler (Demo)',
      email: 'demo.kessler@example.invalid',
      roles: ['support_seeker'],
      createdAt: NOW,
      ageConfirmedAdult: true,
      locale: 'de-DE',
    },
    {
      id: 'u_seeker_2',
      displayName: 'Jonas (Demo)',
      email: 'demo.jonas@example.invalid',
      roles: ['support_seeker'],
      createdAt: NOW,
      ageConfirmedAdult: true,
      locale: 'de-DE',
    },
    {
      id: 'u_provider_1',
      displayName: 'Meike (Demo)',
      email: 'demo.meike@example.invalid',
      roles: ['provider'],
      createdAt: NOW,
      ageConfirmedAdult: true,
      locale: 'de-DE',
    },
    {
      id: 'u_provider_2',
      displayName: 'Tarek (Demo)',
      email: 'demo.tarek@example.invalid',
      roles: ['provider'],
      createdAt: NOW,
      ageConfirmedAdult: true,
      locale: 'de-DE',
    },
    {
      id: 'u_provider_3',
      displayName: 'Bettina (Demo)',
      email: 'demo.bettina@example.invalid',
      roles: ['provider'],
      createdAt: NOW,
      ageConfirmedAdult: true,
      locale: 'de-DE',
    },
    {
      id: 'u_trusted_1',
      displayName: 'Herr Kessler (Demo)',
      email: 'demo.kessler.sohn@example.invalid',
      roles: ['trusted_person'],
      createdAt: NOW,
      ageConfirmedAdult: true,
      locale: 'de-DE',
    },
    {
      id: 'u_reviewer_1',
      displayName: 'Prüfstelle A (Demo)',
      email: 'demo.pruefung.a@example.invalid',
      roles: ['reviewer'],
      createdAt: NOW,
      ageConfirmedAdult: true,
      locale: 'de-DE',
    },
    {
      id: 'u_admin_1',
      displayName: 'Verwaltung (Demo)',
      email: 'demo.verwaltung@example.invalid',
      roles: ['admin'],
      createdAt: NOW,
      ageConfirmedAdult: true,
      locale: 'de-DE',
    },
  ],

  seekers: [
    {
      userId: 'u_seeker_1',
      region: { postalPrefix: '221', city: 'Hamburg', approxLat: 53.55, approxLon: 9.99 },
      supportNeeds: ['Ich brauche jemanden, der mit mir zu Terminen geht.'],
      mobilityNotes: 'Ich benutze einen Rollator. Treppen gehen nicht.',
      communicationModes: ['sprechen', 'leichte_sprache'],
      languages: ['Deutsch'],
      sharedBeforeBooking: ['displayName', 'region', 'communicationModes', 'languages'],
      aboutMe: 'Ich wohne seit vierzig Jahren in Hamburg und gehe gern spazieren.',
      photoUrl: null,
      photoAltText: null,
      preciseAddress: {
        street: 'Beispielweg',
        houseNumber: '12',
        postalCode: '22111',
        city: 'Hamburg',
      },
      phone: '+49 40 000000 (Demo)',
      updatedAt: NOW,
    },
    {
      userId: 'u_seeker_2',
      region: { postalPrefix: '203', city: 'Hamburg', approxLat: 53.57, approxLon: 9.97 },
      supportNeeds: ['Ich möchte beim Einkaufen begleitet werden.'],
      communicationModes: ['dgs', 'schreiben'],
      languages: ['Deutsch', 'Deutsche Gebärdensprache'],
      sharedBeforeBooking: ['displayName', 'region', 'communicationModes'],
      aboutMe: 'Ich bin gehörlos und verständige mich in Gebärdensprache.',
      photoUrl: null,
      photoAltText: null,
      preciseAddress: null,
      phone: null,
      updatedAt: NOW,
    },
  ],

  providers: [
    {
      userId: 'u_provider_1',
      kind: 'professional',
      region: { postalPrefix: '221', city: 'Hamburg', approxLat: 53.56, approxLon: 9.98 },
      radiusKm: 15,
      headline: 'Heilerziehungspflegerin, begleitet zu Terminen und im Alltag',
      aboutMe:
        'Ich arbeite seit zwölf Jahren in der Eingliederungshilfe. Mir ist wichtig, dass wir vorher besprechen, wie Sie es gern hätten. Ich rede nicht über Sie, sondern mit Ihnen.',
      explicitlyNotOffered: ['Keine Wohnungsreinigung', 'Keine Fahrten mit dem eigenen Auto'],
      languages: ['Deutsch', 'Englisch'],
      communicationModes: ['sprechen', 'schreiben', 'leichte_sprache'],
      signLanguageLevel: 'basic',
      signLanguageVerified: false,
      accessibilitySkills: ['Rollator', 'Rollstuhl', 'Leichte Sprache', 'Demenz'],
      photoUrl: null,
      photoAltText: null,
      introVideoUrl: null,
      volunteer: false,
      hourlyRateCents: 2800,
      cancellationPolicy: 'Bis 24 Stunden vorher kostenlos. Danach die Hälfte.',
      hasMobility: true,
      updatedAt: NOW,
    },
    {
      userId: 'u_provider_2',
      kind: 'qualified_companion',
      region: { postalPrefix: '203', city: 'Hamburg', approxLat: 53.57, approxLon: 9.96 },
      radiusKm: 10,
      headline: 'Alltagsbegleiter, gebärdensprachkompetent',
      aboutMe:
        'Ich bin in einer gehörlosen Familie aufgewachsen. Beim Einkaufen und bei Behördengängen bin ich in Ruhe dabei und dolmetsche nicht, sondern begleite.',
      explicitlyNotOffered: ['Keine pflegerischen Tätigkeiten', 'Kein Dolmetschen bei Gericht'],
      languages: ['Deutsch', 'Deutsche Gebärdensprache'],
      communicationModes: ['dgs', 'schreiben', 'sprechen'],
      signLanguageLevel: 'native',
      signLanguageVerified: true,
      accessibilitySkills: ['Gebärdensprache', 'Gehörlosigkeit', 'Behördengänge'],
      photoUrl: null,
      photoAltText: null,
      introVideoUrl: null,
      volunteer: false,
      hourlyRateCents: 2200,
      cancellationPolicy: 'Bis 24 Stunden vorher kostenlos.',
      hasMobility: false,
      updatedAt: NOW,
    },
    {
      userId: 'u_provider_3',
      kind: 'private_helper',
      region: { postalPrefix: '221', city: 'Hamburg', approxLat: 53.54, approxLon: 10.01 },
      radiusKm: 8,
      headline: 'Nachbarschaftshilfe, ehrenamtlich',
      aboutMe:
        'Ich bin seit einem Jahr in Rente und habe zwei Vormittage in der Woche Zeit. Spazierengehen, Vorlesen, ein Schwatz bei Kaffee.',
      explicitlyNotOffered: ['Keine pflegerischen Tätigkeiten', 'Kein Heben und Tragen'],
      languages: ['Deutsch'],
      communicationModes: ['sprechen', 'leichte_sprache'],
      signLanguageLevel: 'none',
      signLanguageVerified: false,
      accessibilitySkills: ['Leichte Sprache', 'Geduld bei langsamer Sprache'],
      photoUrl: null,
      photoAltText: null,
      introVideoUrl: null,
      volunteer: true,
      hourlyRateCents: null,
      cancellationPolicy: 'Absage jederzeit möglich, kostenlos.',
      hasMobility: false,
      updatedAt: NOW,
    },
  ],

  services: [
    { providerId: 'u_provider_1', categoryKey: 'begleitung_termine', experienceYears: 12 },
    { providerId: 'u_provider_1', categoryKey: 'einkaufen', experienceYears: 8 },
    { providerId: 'u_provider_1', categoryKey: 'freizeit_teilhabe', experienceYears: 10 },
    { providerId: 'u_provider_1', categoryKey: 'pflegerische_unterstuetzung', experienceYears: 12 },
    { providerId: 'u_provider_2', categoryKey: 'begleitung_termine', experienceYears: 5 },
    { providerId: 'u_provider_2', categoryKey: 'einkaufen', experienceYears: 5 },
    { providerId: 'u_provider_2', categoryKey: 'kommunikation', experienceYears: 6 },
    { providerId: 'u_provider_3', categoryKey: 'spaziergang', experienceYears: 1 },
    { providerId: 'u_provider_3', categoryKey: 'vorlesen', experienceYears: 1 },
    { providerId: 'u_provider_3', categoryKey: 'begleitung_termine', experienceYears: 1 },
  ],

  verifications: [
    {
      id: 'ver_1',
      providerId: 'u_provider_1',
      qualificationKey: 'identitaet',
      status: 'approved',
      submittedAt: NOW,
      decidedAt: NOW,
      decidedBy: 'u_reviewer_1',
      secondApproverId: null,
      validUntil: null,
      rejectionReason: null,
      documentPath: null,
    },
    {
      id: 'ver_2',
      providerId: 'u_provider_1',
      qualificationKey: 'heilerziehungspflege',
      status: 'approved',
      submittedAt: NOW,
      decidedAt: NOW,
      decidedBy: 'u_reviewer_1',
      secondApproverId: 'u_admin_1',
      validUntil: null,
      rejectionReason: null,
      documentPath: null,
    },
    {
      id: 'ver_3',
      providerId: 'u_provider_2',
      qualificationKey: 'identitaet',
      status: 'approved',
      submittedAt: NOW,
      decidedAt: NOW,
      decidedBy: 'u_reviewer_1',
      secondApproverId: null,
      validUntil: null,
      rejectionReason: null,
      documentPath: null,
    },
    {
      id: 'ver_4',
      providerId: 'u_provider_2',
      qualificationKey: 'dgs_kompetenz',
      status: 'approved',
      submittedAt: NOW,
      decidedAt: NOW,
      decidedBy: 'u_reviewer_1',
      secondApproverId: null,
      validUntil: null,
      rejectionReason: null,
      documentPath: null,
    },
    {
      id: 'ver_5',
      providerId: 'u_provider_2',
      qualificationKey: 'alltagsbegleitung_43b',
      status: 'approved',
      submittedAt: NOW,
      decidedAt: NOW,
      decidedBy: 'u_reviewer_1',
      secondApproverId: null,
      validUntil: null,
      rejectionReason: null,
      documentPath: null,
    },
    {
      id: 'ver_6',
      providerId: 'u_provider_3',
      qualificationKey: 'identitaet',
      status: 'approved',
      submittedAt: NOW,
      decidedAt: NOW,
      decidedBy: 'u_reviewer_1',
      secondApproverId: null,
      validUntil: null,
      rejectionReason: null,
      documentPath: null,
    },
    {
      id: 'ver_7',
      providerId: 'u_provider_3',
      qualificationKey: 'erste_hilfe',
      status: 'approved',
      submittedAt: NOW,
      decidedAt: NOW,
      decidedBy: 'u_reviewer_1',
      secondApproverId: null,
      // Laeuft demnaechst ab -- zeigt im Adminbereich die Erinnerung.
      validUntil: '2026-03-20',
      rejectionReason: null,
      documentPath: null,
    },
    {
      id: 'ver_8',
      providerId: 'u_provider_3',
      qualificationKey: 'fuehrungszeugnis_erweitert',
      status: 'pending',
      submittedAt: NOW,
      decidedAt: null,
      decidedBy: null,
      secondApproverId: null,
      validUntil: null,
      rejectionReason: null,
      documentPath: null,
    },
  ],

  // Montag bis Freitag vormittags; Dienstag zusaetzlich nachmittags.
  availability: [
    ...[1, 2, 3, 4, 5].map((weekday) => ({
      id: `slot_p1_${weekday}`,
      providerId: 'u_provider_1',
      weekday,
      startMinute: 8 * 60,
      endMinute: 16 * 60,
      recurring: true,
      date: null,
    })),
    ...[1, 3, 5].map((weekday) => ({
      id: `slot_p2_${weekday}`,
      providerId: 'u_provider_2',
      weekday,
      startMinute: 9 * 60,
      endMinute: 18 * 60,
      recurring: true,
      date: null,
    })),
    ...[2, 4].map((weekday) => ({
      id: `slot_p3_${weekday}`,
      providerId: 'u_provider_3',
      weekday,
      startMinute: 9 * 60,
      endMinute: 12 * 60,
      recurring: true,
      date: null,
    })),
  ],

  absences: [
    {
      id: 'abs_1',
      providerId: 'u_provider_1',
      from: '2026-04-01',
      to: '2026-04-14',
      reason: 'Urlaub',
    },
  ],

  preferences: [
    { ...createDefaultPreferences('u_seeker_1', 'einfach', NOW) },
    {
      ...createDefaultPreferences('u_seeker_2', 'individuell', NOW),
      signLanguage: true,
      captions: true,
      readAloud: false,
    },
  ],

  consents: [
    ...(['terms', 'privacy', 'sensitive_support_needs', 'location_coarse', 'contact_release'] as const).map(
      (purpose, i) => ({
        id: `cons_s1_${i}`,
        userId: 'u_seeker_1',
        purpose,
        granted: true,
        policyVersion: '2026-01-01',
        grantedAt: NOW,
        revokedAt: null,
        channel: 'tap' as const,
        assistedBy: null,
      }),
    ),
    ...(['terms', 'privacy', 'sensitive_support_needs', 'location_coarse'] as const).map((purpose, i) => ({
      id: `cons_s2_${i}`,
      userId: 'u_seeker_2',
      purpose,
      granted: true,
      policyVersion: '2026-01-01',
      grantedAt: NOW,
      revokedAt: null,
      channel: 'tap' as const,
      assistedBy: null,
    })),
    ...(['terms', 'privacy'] as const).flatMap((purpose) =>
      ['u_provider_1', 'u_provider_2', 'u_provider_3'].map((userId) => ({
        id: `cons_${userId}_${purpose}`,
        userId,
        purpose,
        granted: true,
        policyVersion: '2026-01-01',
        grantedAt: NOW,
        revokedAt: null,
        channel: 'tap' as const,
        assistedBy: null,
      })),
    ),
  ],

  trust: [
    {
      id: 'trust_1',
      seekerId: 'u_seeker_1',
      trustedPersonId: 'u_trusted_1',
      scopes: ['view_profile', 'create_requests', 'read_messages'],
      createdAt: NOW,
      expiresAt: null,
      revokedAt: null,
      legalBasisNote: 'Auf ausdrücklichen Wunsch von Frau Kessler. Keine gesetzliche Betreuung.',
    },
  ],

  reviews: [
    {
      id: 'rev_demo_1',
      bookingId: 'book_demo_1',
      authorId: 'u_seeker_2',
      subjectId: 'u_provider_1',
      rating: 3,
      publicComment: 'Hat sich Zeit genommen und alles vorher erklärt.',
      privateFeedback: null,
      createdAt: NOW,
    },
  ],
};
